---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  HTTPResponse:
    Type: Number
    Default: 302
    AllowedValues: [301, 302]
    Description: "The HTTP response status code."
  NewDomain:
    Type: String
    Description: "New domain to redirect to."
  StageName:
    Type: String
    Description: "Name of the stage. Caveat: https://github.com/awslabs/serverless-application-model/issues/191"
  SwaggerFileBucket:
    Type: String
    Description: "Name of the S3 bucket holds the Swagger file defined in 'SwaggerFileName'. Eg: 'MyS3Bucket'."
  SwaggerFileName:
    Type: String
    Description: "The file name of the swagger file. Eg: 'swagger.yml'."
Resources:
  Listener:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: StageName
      DefinitionBody:
          # See: https://thomasvachon.com/articles/making-modular-cloudformation-with-includes/
          'Fn::Transform':
            Name: 'AWS::Include'
            Parameters:
              Location: !Join ['/', ['s3:/', !Ref SwaggerFileBucket, !Ref SwaggerFileName]]
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: redirector.get
      Runtime: nodejs6.10
      Policies: AWSLambdaBasicExecutionRole
      FunctionName: !Join ['-', ['get', !Ref 'AWS::StackName']]
      Tags: 
        AppNameTag: GetHandler
      Environment:
        Variables:
          NEW_DOMAIN: !Ref NewDomain
          HTTP_RESPONSE: !Ref HTTPResponse
  AnyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: redirector.any
      Runtime: nodejs6.10
      Policies: AWSLambdaBasicExecutionRole
      FunctionName: !Join ['-', ['any', !Ref 'AWS::StackName']]
      Tags: 
        AppNameTag: AnyHandler
      Environment:
        Variables:
          NEW_DOMAIN: !Ref NewDomain
          HTTP_RESPONSE: !Ref HTTPResponse
  LambdaGetPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
    - GetFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetFunction
      Principal: apigateway.amazonaws.com
  LambdaAnyPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
    - AnyFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AnyFunction
      Principal: apigateway.amazonaws.com